# Generated by Django 4.0 on 2023-04-16 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FriendsThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('RECEIVED', 'RECEIVED')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworkUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='social_network', through='core.FriendsThrough', to='core.SocialNetworkUsers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='friendsthrough',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='core.socialnetworkusers'),
        ),
        migrations.AddField(
            model_name='friendsthrough',
            name='social_network_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='core.socialnetworkusers'),
        ),
        migrations.AddConstraint(
            model_name='friendsthrough',
            constraint=models.UniqueConstraint(fields=('social_network_user', 'friend', 'relationship_type'), name='unique_social_friend_relation'),
        ),
        migrations.AddConstraint(
            model_name='friendsthrough',
            constraint=models.CheckConstraint(check=models.Q(('social_network_user', django.db.models.expressions.F('friend')), _negated=True), name='user_not_as_friend'),
        ),
    ]
